version: "3"
services:
  api:
    build:
      context: ./packages/api/
    container_name: api
    command: yarn start
    ports:
      - "8080:8080"
    volumes:
      - ./packages/api/:/api
      - /packages/api/node_modules
  app:
    build:
      context: ./packages/app/
    container_name: react-app
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./packages/app/:/app
      - /packages/app/node_modules
    depends_on:
      - api
